# Generated by Django 3.1.1 on 2021-02-08 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_management', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('sap_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=13)),
                ('department', models.CharField(choices=[('CS', 'COMPUTERS'), ('IT', 'INFORMATION TECHNOLOGY'), ('EXTC', 'ELECTRONICS AND TELECOMMUNICATION'), ('ELEX', 'ELECTRONICS'), ('MECH', 'MECHANICAL'), ('CHEM', 'CHEMICAL'), ('BIOMED', 'BIOMED'), ('PROD', 'PRODUCTION'), ('OTHERS', 'OTHERS')], max_length=40)),
                ('admission_year', models.CharField(max_length=5)),
                ('marksheet', jsonfield.fields.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementProfile',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=13)),
                ('accepted', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
