# Generated by Django 3.1.5 on 2021-02-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('In Queue', 'In Queue'), ('In Review', 'In Review'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('in_review', models.BooleanField(default=False)),
                ('application_file', models.FileField(upload_to='')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.managementprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
        ),
    ]
