# Generated by Django 3.1.5 on 2021-02-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
