# Generated by Django 3.1.5 on 2021-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='marksheet',
            field=models.JSONField(),
        ),
    ]
