# Generated by Django 3.1.5 on 2021-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210628_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='marksheet',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
