# Generated by Django 3.1.5 on 2021-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210720_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='marksheet',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
