# Generated by Django 3.1.5 on 2021-04-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210430_1125'),
        ('core', '0004_auto_20210420_1812'),
    ]

    operations = [
    ]
