# Generated by Django 3.1.5 on 2021-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20210430_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='marks'),
        ),
    ]
