# Generated by Django 3.1.5 on 2021-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210430_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='semester',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='file',
            field=models.FileField(default=0, upload_to='marks'),
            preserve_default=False,
        ),
    ]
