# Generated by Django 3.1.5 on 2021-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210612_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='marks_copy',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
