# Generated by Django 3.1.5 on 2021-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_application_marks_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='marks_copy',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
